<?php

/**
 * Fired during plugin deactivation
 *
 * @link       https://joshuacabo.com
 * @since      2.7.8
 *
 * @package    umifuzug
 * @subpackage umifuzug/includes
 */

/**
 * Fired during plugin deactivation.
 *
 * This class defines all code necessary to run during the plugin's deactivation.
 *
 * @since      2.7.8
 * @package    umifuzug
 * @subpackage umifuzug/includes
 * @author     Joshuacabo <joshuacabo@gmail.com>
 */
 

 
class umifuzug_Deactivator {

	/**
	 * Short Description. (use period)
	 *
	 * Long Description.
	 *
	 * @since    2.7.8
	 */
	public static function deactivate() {

	}

}
